=== FarmBuild/farmbuild-web-services-demo/docs/schemas/farmbuild-soil-areas-in.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "dateCreated": {
      "type": "string",
      "minLength": 1
    },
    "dateLastUpdated": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "geometry": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1
        },
        "crs": {
          "type": "string",
          "minLength": 1
        },
        "coordinates": {
          "type": "array",
          "items": {
            "required": [],
            "properties": {}
          }
        }
      },
      "required": [
        "type",
        "crs",
        "coordinates"
      ]
    },
    "totalArea": {
      "type": "number"
    },
    "attributes": {
      "type": "object",
      "properties": {
        "attribute": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "value": {
              "type": "number"
            }
          },
          "required": [
            "name",
            "value"
          ]
        }
      },
      "required": [
        "attribute"
      ]
    },
    "paddocks": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "name",
          "totalArea"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "geometry": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "minLength": 1
              },
              "crs": {
                "type": "string",
                "minLength": 1
              },
              "coordinates": {
                "type": "array",
                "items": {
                  "required": [],
                  "properties": {}
                }
              }
            },
            "required": [
              "type",
              "crs",
              "coordinates"
            ]
          },
          "totalArea": {
            "type": "number"
          }
        }
      }
    },
    "managementGroups": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "required": [
          "number",
          "name",
          "description"
        ],
        "properties": {
          "number": {
            "type": "string",
            "minLength": 1
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "description": {
            "type": "string",
            "minLength": 1
          },
          "paddocks": {
            "type": "array",
            "items": {
              "required": [],
              "properties": {}
            }
          }
        }
      }
    }
  },
  "required": [
    "version",
    "dateCreated",
    "dateLastUpdated",
    "name",
    "geometry",
    "totalArea",
    "attributes",
    "paddocks",
    "managementGroups"
  ]
}

=== FarmBuild/farmbuild-web-services-demo/json/farmbuild-soil-areas-in.json
{
  "version" : 1.0,
  "dateCreated" : "2015-03-30T21:19:00",
  "dateLastUpdated" : "2015-03-30T21:19:06",
  "name" : "Susan's Farm",
  "geometry" : {
    "type": "Polygon",
    "crs": "EPSG:4283",
    "coordinates": []
  },
  "totalArea" : 28.09,
  "attributes" : {
    "attribute" : {
      "name" : "milkingArea_ha",
      "value" : 23.34
    }
  },
  "paddocks" : [
    {
      "name" : "P3",
      "geometry" : {
        "type": "Polygon",
        "crs": "EPSG:4283",
        "coordinates": []
      },
      "totalArea" : 0.72
    },
    {
      "name" : "P1",
      "geometry" : {
        "type": "Polygon",
        "crs": "EPSG:4283",
        "coordinates": []
      },
      "totalArea" : 0.87
    }
  ],
  "managementGroups" : [
    {
      "number" : "1",
      "name" : "Group 1",
      "description" : "Night Paddocks",
      "paddocks": ["P3"]
    },
    {
      "number" : "2",
      "name" : "Group 2",
      "description" : "Effluent",
      "paddocks": ["P1"]
    }
  ]
}
